# Generated by Django 4.1 on 2022-08-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='isVisible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
