# Generated by Django 4.1 on 2022-08-26 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_credit_options_assets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assets',
            new_name='Asset',
        ),
    ]
